<?php

namespace Dentaku\Redmine\Repository\Projects;

use Dentaku\Redmine\Model\AbstractModel;
use Dentaku\Redmine\Model\Project\IssueCategory;
use Dentaku\Redmine\Repository\AbstractRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Error;

class IssueCategories extends AbstractRepository
{
    public const API_ROOT = "issue_categories";

    protected function getModelClass(): string
    {
        return IssueCategory::class;
    }

    public function all(): ArrayCollection
    {
        throw new Error("Method not implemented for apì: " . self::API_ROOT);
    }

    public function search(array $params = []): ArrayCollection
    {
        throw new Error("Method not implemented for apì: " . self::API_ROOT);
    }

    public function delete(AbstractModel $model): void
    {
        if ($model->getReassignTo() !== null) {
            $endpoint_url = $this->getEndpoint() . "/" . $model->getId() . "." . $this->client->getFormat() . "?reassign_to_id=" . $model->getReassignTo()->getId();
            $this->client->delete($endpoint_url);
        } else {
            parent::delete($model); // TODO: Change the autogenerated stub
        }

    }

}