<?php

namespace Dentaku\Redmine\Collection;

class RepeatableIdCollection extends IdentityCollection
{
    public function toArray(): array
    {
        $ret = [];
        $elements = parent::toArray(); // TODO: Change the autogenerated stub
        foreach ($elements as $element) {
            $ret[] = $element["id"];
        }

        return $ret;

    }
}